# -*- coding: utf-8 -*-
"""DiseaseDiagnose.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFw_AKGGNk7JX_oxluVhXhgi_9Yraoo3
"""

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

# =========================
# 1. LOAD DATA
# =========================
df = pd.read_csv("vitals_dataset.csv")
print(df)
# =========================
# 2. USE ONLY REQUIRED FEATURES
# =========================
features = [
    "Heart Rate (bpm)",
    "SpO2 Level (%)",
    "Body Temperature (°C)",
]

df = df.dropna(subset=features)

# =========================
# 3. CREATE ABNORMALITY LABELS
# =========================
def label_abnormal(row):
    hr = row["Heart Rate (bpm)"]
    spo2 = row["SpO2 Level (%)"]
    temp = row["Body Temperature (°C)"]

    abnormalities = []

    # Heart Rate
    if hr < 60:
        abnormalities.append("Heart Rate Too Low")
    elif hr > 100:
        abnormalities.append("Heart Rate Too High")

    # SpO2
    if spo2 < 95:
        abnormalities.append("SpO2 Too Low")

    # Temperature
    if temp < 35:
        abnormalities.append("Temperature Too Low")
    elif temp >= 38:
        abnormalities.append("Temperature Too High")

    if len(abnormalities) == 0:
        return "Normal"

    return " | ".join(abnormalities)

#df["Abnormality"] = df.apply(label_abnormal, axis=1)

# =========================
# 4. ENCODE LABELS
# =========================
X = df[features]
#y = df["Abnormality"]
y = df['Predicted Disease']


encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)


# =========================
# 5. TRAIN TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

# =========================
# 6. TRAIN MODEL
# =========================
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# =========================
# 7. EVALUATE
# =========================
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

# =========================
# 8. SAVE MODEL
# =========================
joblib.dump(model, "abnormality_model.pkl")
joblib.dump(encoder, "abnormality_encoder.pkl")

print("Model saved successfully.")

model = joblib.load("abnormality_model.pkl")
encoder = joblib.load("abnormality_encoder.pkl")

def check_vitals(hr, spo2, temp):

    input_data = np.array([[hr, spo2, temp]])
    prediction = model.predict(input_data)
    result = encoder.inverse_transform(prediction)[0]

    print("\n--- Vital Analysis ---")
    print(f"Heart Rate: {hr} bpm")
    print(f"SpO2: {spo2}%")
    print(f"Temperature: {temp}°C")


    abnormalities = []
    result2 = ""
    # Heart Rate
    if hr < 60:
        abnormalities.append("Heart Rate Too Low")
    elif hr > 100:
        abnormalities.append("Heart Rate Too High")

    # SpO2
    if spo2 < 95:
        abnormalities.append("SpO2 Too Low")

    # Temperature
    if temp < 35:
        abnormalities.append("Temperature Too Low")
    elif temp >= 38:
        abnormalities.append("Temperature Too High")

    result2 = abnormalities
    if len(abnormalities) == 0:
        result2 = "Normal"

    if result2 == "Normal":
        print("Status: All vitals within normal range.")
    else:
        print("Status: Abnormalities detected:")
        print(result2)
        print(result)
        print("Recommendation: Consider medical evaluation if symptoms persist.")

    print("-----------------------\n")

check_vitals(90, 98, 38)