# -*- coding: utf-8 -*-
"""riskpredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WVv5wdvpwMPnPC0O2iGk6IfjkcO5r9A
"""

# -*- coding: utf-8 -*-

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# =========================
# LOAD DATA
# =========================
df = pd.read_csv("vitals_dataset.csv")

# print("Dataset preview:")
# print(df.head())

# =========================
# SELECT FEATURES
# =========================
features = [
    "Heart Rate (bpm)",
    "SpO2 Level (%)",
    "Body Temperature (°C)"
]

df = df.dropna(subset=features)

# =========================
# CREATE RISK LABEL
# =========================
# Convert disease column to binary risk label
# 0 = normal
# 1 = some disease present

df["RiskLabel"] = df["Predicted Disease"].apply(
    lambda x: 0 if str(x).strip().lower() == "healthy" else 1
)
print(df["RiskLabel"])

# =========================
# PREPARE DATA
# =========================
X = df[features]
y = df["RiskLabel"]

# =========================
# TRAIN TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================
# TRAIN MODEL
# =========================
model = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42
)

model.fit(X_train, y_train)

# =========================
# EVALUATE MODEL
# =========================
y_pred = model.predict(X_test)

print("\nModel Evaluation:")
print(classification_report(y_test, y_pred))

# =========================
# SAVE MODEL
# =========================
joblib.dump(model, "risk_model.pkl")

print("\nModel saved successfully.")

# =========================
# LOAD MODEL
# =========================
model = joblib.load("risk_model.pkl")

# =========================
# RISK LEVEL FUNCTION
# =========================
def get_risk_level(score):

    if score < 30:
        return "Low Risk"
    elif score < 60:
        return "Moderate Risk"
    else:
        return "High Risk"

# =========================
# CHECK VITALS FUNCTION
# =========================
def check_vitals(hr, spo2, temp):

    input_data = np.array([[hr, spo2, temp]])

    # Probability of disease
    probs = model.predict_proba(input_data)

    risk_score = probs[0][1] * 100

    risk_level = get_risk_level(risk_score)

    abnormalities = []
    result2 = ""
    # Heart Rate
    if hr < 60:
        abnormalities.append("Heart Rate Too Low")
    elif hr > 100:
        abnormalities.append("Heart Rate Too High")

    # SpO2
    if spo2 < 95:
        abnormalities.append("SpO2 Too Low")

    # Temperature
    if temp < 35:
        abnormalities.append("Temperature Too Low")
    elif temp >= 38:
        abnormalities.append("Temperature Too High")
    result2 = abnormalities

    print("\n--- Vital Analysis ---")
    print(f"Heart Rate: {hr} bpm")
    print(f"SpO2: {spo2}%")
    print(f"Temperature: {temp}°C")

    print(result2)

    print(f"\nRisk Score: {risk_score:.2f}/100")
    print(f"Risk Level: {risk_level}")

    if risk_level == "Low Risk":
        print("Recommendation: Vitals appear normal.")
    elif risk_level == "Moderate Risk":
        print("Recommendation: Monitor symptoms and consider medical advice.")
    else:
        print("Recommendation: Seek medical evaluation.")

    print("-----------------------\n")




# =========================
# TEST EXAMPLE
# =========================
check_vitals(90, 98, 38)